name: python CI 

on: 
  push: 
    branches: [ "main" ]

jobs: 

    build: 
      runs-on: ubuntu-latest 

      steps: 
      - uses: actions/checkout@v3
      - name: Setup python 3.10 
        uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python test_hola_mundo.py
    sonarcloud:
      needs: [build]
      if: success()
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    deploy: 
        name: deploy 
        needs: [sonarcloud] 
        runs-on: ubuntu-latest 
        steps: 
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with: 
              service-id: ${{ secrets.SECRET_ID }}
              api-key: ${{ secrets.SECRET_KEY }}
    messageFailed: 
        needs: [build]
        if: failure()
        runs-on: ubuntu-latest
        steps: 
          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: general
              SLACK_COLOR: '#fc1500'
              SLACK_ICON: https://octodex.github.com/images/Sentrytocat_octodex.jpg
              SLACK_MESSAGE: 'Fallo al hacer el build'
              SLACK_TITLE: Build Status
              SLACK_USERNAME: Slack Bot
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    messageSuccesful: 
        needs: [deploy]
        if: success()
        runs-on: ubuntu-latest
        steps: 
          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            env:
              SLACK_CHANNEL: general
              SLACK_COLOR: '#00fc4c'
              SLACK_ICON: https://octodex.github.com/images/Sentrytocat_octodex.jpg
              SLACK_MESSAGE: 'Build exitoso'
              SLACK_TITLE: Build Status
              SLACK_USERNAME: Slack Bot
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
